using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace SiteGenerator.Templates
{
    class Template
    {
        public const string _Template =
@"@*This file was autogenerated by SiteGenerator, 
manual changes are discouraged as this file will 
be overwritten upon regeneration.*@
@inherits Umbraco.Web.Mvc.UmbracoTemplatePage
@using {constants_namespace}
@{
	"+"Layout = \"BaseLayout.cshtml\";"+@"
}
{partials}
";

        public const string PartialLineTemplate = "@Umbraco.RenderMacro(Macros.{partial_name}.Alias)";

        public string Name;
        public string Path;

        public Template(string targetNamespace, string templateAlias, string baseFSPath)
        {
            Name = templateAlias;
            Path = string.Format("{0}\\Views\\{1}.cshtml", baseFSPath, Name);
        }
    }
}
