using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace SiteGenerator.Templates.Constants
{
    class Macros
    {
        public const string Template =
@"/*
 * This file was autogenerated by SiteGenerator, 
 * manual changes are discouraged as this file will 
 * be overwritten upon regeneration.
 */
using SiteGenerator.Models;

namespace {constants_namespace}
{
    public class Macros
    {
{macro_definitions}
    }
}";
        public const string MacroDefinitionTemplate = "        public static readonly Macro {partial_alias} = new Macro { Alias = \"{partial_alias}\", PartialPath = \"{partial_path}\" };";

        public string Namespace;
        public string Name;
        public string FullName;
        public string Path;

        public Macros(string targetNamespace, string baseFSPath)
        {
            Namespace = string.Format("{0}.Constants", targetNamespace);
            Name = "Macros";
            FullName = string.Format("{0}.{1}", Namespace, Name);
            Path = string.Format("{0}\\Constants\\Macros.cs", baseFSPath);
        }
    }
}
