/*
 * This file was autogenerated by SiteGenerator, 
 * manual changes are discouraged as this file will 
 * be overwritten upon regeneration.
 */
using SiteGenerator.Models;

namespace Website.Constants
{
    public class Macros
    {
        public static readonly Macro CommonHeader = new Macro { Alias = "CommonHeader", PartialPath = "~/Views/Partials/Common/Header.cshtml" };
        public static readonly Macro HomepageContent = new Macro { Alias = "HomepageContent", PartialPath = "~/Views/Partials/Homepage/Content.cshtml" };
        public static readonly Macro ContactpageContent = new Macro { Alias = "ContactpageContent", PartialPath = "~/Views/Partials/Contactpage/Content.cshtml" };
        public static readonly Macro CommonFooter = new Macro { Alias = "CommonFooter", PartialPath = "~/Views/Partials/Common/Footer.cshtml" };
        public static readonly Macro RTEImage = new Macro { Alias = "RTEImage", PartialPath = "~/Views/Partials/RTE/Image.cshtml" };
        public static readonly Macro AboutpageContent = new Macro { Alias = "AboutpageContent", PartialPath = "~/Views/Partials/Aboutpage/Content.cshtml" };
        public static readonly Macro AboutpageCTA = new Macro { Alias = "AboutpageCTA", PartialPath = "~/Views/Partials/Aboutpage/CTA.cshtml" };

    }
}